API_KEY = "YOUR_API_KEY"
# Scraping settings
MAX_LISTINGS_PER_PAGE = 50
DELAY_BETWEEN_PAGES = 2
DELAY_BETWEEN_LISTINGS = 2

# LLM settings
LLM_MODEL = "gpt-4o-mini"
PRINT_PROMPT = False

PAGES_TO_SCRAPE = 2
